### ISSUE TITLE
Long lists jump to the bottom when making changes

### ISSUE THREAD

**Issue by phantomlord2oo** [Automattic/simplenote-android#1580]
[Type] Bug

### Expected

Long lists jump to the bottom when making changes

### Observed
When editing a long list (like my grocery list) whenever I make a change the app automatically jumps to the end of the list.

### Reproduced
List with around 77 lines will jump to bottom of the list after making a change to anywhere else on the list (even changing just 1 character).

 If you reproduced the bug on a specific device, please include the details of the device and app.  For example:
Device Make: Samsung
Device Model: Galaxy S21
Android Version: 13
Simplenote Version: 2.25 (153)

**Comment by joashrajin** [comment]
+1 at 5857035-zd-woothemes

**Comment by reginabally** [comment]
> Really good usually but there's a problem using it now on my Samsung s21 phone, cursor jumps to the end of the note when I'm using it. Really really annoying. I might have to stop using this. Really hope this can be fixed...

Device: Samsung Galaxy S21 5G
App version name: 2.25
Android version: Android 13 (SDK 33)

[4-star app review](https://play.google.com/console/u/0/developers/7957760354032996428/app/4975233711145652703/user-feedback/review-details?reviewId=d35eff96-88d5-4380-b6a6-f80e0640e778&corpus=PUBLIC_REVIEWS)

**Comment by reginabally** [comment]
> Used to work smoothly, but now view shifts unbidden to the end of text if you're editing at a point higher up. This seems to happen if you pause briefly. The cursor stays where you were, but the viewing pane moves to the bottom of the text. This makes editing a longer note all but impossible.

Device: Samsung Galaxy S20
App version name: 2.25
Android version: Android 13 (SDK 33)

[1-star app review](https://play.google.com/console/u/0/developers/7957760354032996428/app/4975233711145652703/user-feedback/review-details?reviewId=4e9c1741-3209-4354-9ae1-d4efdb1b66d6&corpus=PUBLIC_REVIEWS)

**Comment by CameronMilliken** [comment]
I have used your app for years (8 maybe) and loved it that whole time! Unfortunately recently it has been spontaneously scrolling to the bottom of the note intermittently while the app is open; it's becoming unusable since I can't reliably type, or read through my note/s without having to scroll through multiple times. The cursor stays in place.

**Comment by thabotswana** [comment]
>Lately, whenever I update or change a current note that is long, the software constantly brings me back to the bottom of the note instead of keeping me at the place I'm editing. This means that when I pause for even a second, I have to scroll up to find the area I'm changing, even after adding or deleting one letter or character. I can't see what I'm doing without always scrolling up.

DEVICE: Samsung Galaxy S21 5G
DEVICE MODEL: SM-G991U
OPERATING SYSTEM: Android Version 13
SIMPLENOTE VERSION: 2.25 (153)

5996920-zen

**Comment by rezzap** [comment]
> When I go into a note it takes me to the bottom of the note. If I put the cursor at the beginning of the note, the cursor stays there but after a few seconds the screen goes to the bottom of the page.

Device is Samsung Galaxy Tab S6 Lite
Version P610XXU2FWA5/P6100LM2FWA5
Simplenote version 2.25

I have replicated the issue on a Samsung Galaxy Tab S7+ 
Android version 13
Simplenote 2.25 (153)

Steps to replicate: 

1. Open a long note and click anywhere within the note itself to add text or edit. 
2. After a few seconds the focus of the screen will jump to lower in the page. 
3. The cursor remains at it's original space, but the focus is lower. 
4. You need to scroll up to see where your cursor is and the changes being done by the keyboard. 

https://user-images.githubusercontent.com/10325627/223085492-60ea5d64-d27c-4661-85b2-8b0d468497df.mp4




I could not replicate on a Samsung phone (S9+ on Android 10), just the tablet so likely an issue with Android 13.

**Comment by danilo04** [comment]
A new fix was merged in #1585. @rezzap  could you confirm that it solves the issues you were able to reproduce?

**Comment by csoulakian** [comment]
@danilo04 - I can still reproduce this issue.

Device Make: Samsung
Device Model: Galaxy S20
Android Version: 13
One UI Version: 5.1
Simplenote Version: 2.27 (157)

**Comment by roundhill** [comment]
My Galaxy S23 is doing this, I'll take a look!

**Comment by roundhill** [comment]
One workaround for now is to disable Grammarly in the Samsung keyboard settings.

**Comment by notandyvee** [comment]
Hey @rezzap , when you get a chance I have a [draft fix up](https://github.com/Automattic/simplenote-android/pull/1690). Could you try to reproduce it using the buiild in that PR and just test the overall functionality of editing and moving around notes? Would help validate if this does fix things without making other things worse.

**Comment by joashrajin** [comment]
+1 in 10310081-zd-a8c

**Comment by erricgunawan** [comment]
+1 in 10395430-zen
