### ISSUE TITLE
Changes being reverted and not saved when moving between apps

### ISSUE THREAD

**Issue by rezzap** [Automattic/simplenote-android#992]
### Expected

I would expect that when I make changes in the app that changes will be kept if I move to another app or end up on the lock screen. 

### Observed

Changes are not always kept in history when moving between apps or going to lock screen and sometimes are reverted. 

### Reproduced
We weren't able to reproduce this, but the user did provide us with a screen recording of it happening. 
It's available here: https://share.getcloudapp.com/WnuNDrqX
Relevant content between times 1:20~1:40 & 3:00.

Steps to reproduce seem to be: 
> 1. Go to Simplenote app and add some text to a note. 
> 2. Use the app switcher button in the bottom navigation and go to a new app.
> 3. Screen locks. 
> 4. Unlock the phone and go back to Simplenote
> 3. See your changed being reverted and look through history previous changes were not registered. 

Make|Model|Android Version|App Version
-|-|-|-
Samsung|Galaxy 9|10|2.4 & 2.5-rc-1

This user replied with two additional bits of information
>When i finish writing with a note for the moment, i go back to the list view and select the note again to save and sync. It does help. When i do that it syncs to the internet right away. Then the reverse problem doesn't happen.

**Comment by rezzap** [comment]
We have another very similar report for this here: 2777335-zen

They provided these steps to reproduce: 

> 1) Login Chrome web first to check
> 2) Login and edited note on Android app
> 3) Android app goes to background while checking another app
> 4) Back to Android app and all of my editing was gone
> 4-1) That note page looked like refreshing and its page moved onto upside down even I didn't touch
> 4-2) I write several words to test and its gone too. But it wasn't easily reproduced.
> 4-3) Assumption : if android app is going to background while syncing, and back then it seems like to discard local client one and gets from server.
> 5) Checking history on Android app but nothing left
> 6) Checking history on Chrome web but nothing left too.

**Comment by erricgunawan** [comment]
Also got a similar report: 2799194-zen 

Translated: 

> I have used this application a lot on my tablet but for more than a month I have been worried and I will have to find another alternative because the new thing I write does not stay put, when I change my note or when I exit and reenter the application I check what I put and it is not, I write it again and it happens again and, I am left without the new information. Many times I even see how the writing disappears.

Also, 

> There can be nothing in the trash because what disappears are not whole notes, the problem is that the last words or phrases that I add to the notes disappear, when I change the note or close the application, so that when I return to the note where I added those last words or phrases are no longer.

I tried to confirm if they're switching apps or closing the app entirely when the problem occurred.

**Comment by msilbers** [comment]
Asked for additional details but it looks like this was also reported in 2808018-zen

Changes do not sync unless they specifically go to Android Home instead of between apps.

**Comment by rezzap** [comment]
Similar mention of this in 2988723-zen

They mention:

> it happens with any of the bottom 3 buttons on Android: Back, App Switch and Home. However it doesn't always happen, it seems only when the app was unloaded from RAM? That's what it seems like. But if I wait 4-5 seconds before opening another app, it always syncs the changes properly. So far I haven't noticed it happening by going to the main notes list in the app but I'll keep an eye on that.

Samsung Galaxy S9 (SM-G960F). It's using Android 10 with One UI 2.0.
The app is updated to the most recent version: 2.5.1

**Comment by theck13** [comment]
This was fixed in https://github.com/Automattic/simplenote-android/pull/1006, which is included in Simplenote Android 2.6.0 scheduled for release June 1st.  If we get reports of this behavior after updating t0 2.6.0, we should reopen this issue.

**Comment by sarahfg** [comment]
User report of the issue repeating on Simplenote Android 2.6.0 . the issue still persists for me. The user installed version 2.4 from Github and now that resolved the user's issue 

#3076252-zen

**Comment by theck13** [comment]
The user doesn't specify that the issue occurs with Simplenote Android 2.6.0 since they say "the latest version" in the ticket.  Let's confirm they were having issues with Simplenote Android 2.6.0 first.

It's possible just uninstalling and reinstalling the app fixed their syncing issue.  I would suggest that they update to Simplenote Android 2.6.0 to ensure the issue is with the latest version and not a version inbetween.  Simplenote Android 2.4.0 introduced a networking bug that was reverted in Simplenote Android 2.6.0.  Therefore, if they didn't have issues before Simplenote Android 2.4.0, then they shouldn't have issue with Simplenote Android 2.6.0 either.  If they do, then we need to investigate what's happening.  That's why updating from Simplenote Android 2.4.0 to 2.6.0 would help us narrow down the issue.

Also, they don't say if they are using Simplenote on Android exclusively of with other platforms as well.  That will help determine if the issue is indeed Android.

**Comment by erricgunawan** [comment]
This is a report from 3061432-zen, which is a follow-up (or the same user) with [2808018-zen](https://github.com/Automattic/simplenote-android/issues/992#issuecomment-602130328) above.

> I did experience this problem -- losing what I'd just typed if after typing it I switch to a different app -- on 2.6.0, not just on earlier versions.

User said they experienced the issue on their two Android apps: a phone and a tablet.

Their tablet is: Lenovo Tab M8 HD, running Android 9 Pie.
(I'm confirming their Android phone make and model).

They have also upgraded to 2.7:

> My tablet was already on 2.7, and I updated my phone to 2.7.

They said it didn't happen on their Windows web app:

> Now I'm going to write in Simpleapp (browser version) on my Windows PC instead of on Android, at least for right now, because I've only lost data on Android.

(Confirming again).

They did mention that they might be on a slow network:

> I'm stuck with a very slow internet speed from AT&T here because their infrastructure in our neighborhood hasn't been updated since the 1960s.

> Therefore I'm going to assume that when sync takes longer than it's supposed to, it's because of network slowness. (Although the bandwidth required for even a lot of typed text is minimal.)

They made two suggestions/requests:

> So I have two requests (let me know if they make sense):

> 1. Before sync takes place, retain what I just typed in local memory, don't flush it. I don't understand why anything I enter into Simplenote should, under any circumstances, disappear from the device where I have just entered the text in question. Before it syncs, it should stay put and not disappear.

> 2. Give me more control and feedback within the app relative to the sync process. To make sure Simplenote has synced, I should not have to open the note in question on another device to watch sync take effect. On the device where I'm typing I should be able to command Simplenote to sync and get feedback when it completes syncing.

Let me know if there are any further questions y'all would like to ask or need to investigate this further.

**Comment by erricgunawan** [comment]
Possibly another case on 3155291-zen:

> I am having an occassional issue with Simplenote v2.7 on Android 10. From time to time it just wipes out what I have recently typed. If I am lucky I can restore most of it from the history, but often the new text has not been saved to the history either. 

Confirming a couple of things first.

**Comment by erricgunawan** [comment]
3195841-zen:

> ... from time to time, when I open the app and start to edit one of my notes, go back to my notes list, and then go back into the note I just edited, the edits I had just made will disappear.

> The edits don’t appear in the history of the note either.

Simplenote 2.8

Confirming device make and model.

**Comment by reginabally** [comment]
Additional info for 3195841-zen:

Samsung Galaxy S7 (SM-G930T). Android version is 8.0.0.

**Comment by rossanafmenezes** [comment]
Another report here:

3285579-zen

System: Chrome OS Version 84.0.4147.136 (Official Build)
Simple note version 2.9 Android

 Lenovo Chromebook C330

**Comment by rossanafmenezes** [comment]
Another report here 3367531-zen user went from Simplenote app to Google search and when they went back to Simplenote part of the note was gone and it was not in the history. 

Pixel 3
Android 11
Simplenote 2.10.1

**Comment by AliSoftware** [comment]
Another report here: 3375467-zen

Seems to happen when they switch apps (content they added is gone the next time they go into Simplenote.)

Moto G4
Android 7.0
Simplenote 2.12-rc-1 (but it was happening with 2.10 as well)

[EDIT] More context provided by the user:

> Circumstances: Added three lines to the top of a note with 30 or so more lines below it, using voice dictation, and when I next unlocked my phone, with Simplenote still in the foreground, my three new lines were gone -- but when the screen unlocked I saw them very briefly before they disappeared. HOWEVER, a double line return I did with the virtual
keyboard before (or was it after?) adding that voice-dictated text did not disappear.
> 
> So maybe it's a voice-typing thing?

device logs provided by the user in the ticket

**Comment by sshaikh** [comment]
Still seeing the issue on 2.11.1. I initially raised in #1052 - no apparent change in behaviour. Essentially the story is:

1. Edit a note Saturday night on Android device. Make sure to back out of the note, in the (vain?) hope that it forces a sync.
2. Access note on Sunday via electron app on Windows PC. Notice that it's out of date.
3. Go back into android app to confirm note was updated and I wasn't just dreaming what happened the day before.
4. Do a little dance, click my heels three times and make an offering to the cloud gods.
5. Notice that the note in the electron app has updated in the meantime.

Without labouring the point too much, is there any sign of that "last updated/sync status" label? It's mentioned here (https://github.com/Automattic/simplenote-electron/issues/2162) for the electron app but it would make a lot of these issues just easier to bear. If Google Docs can do it I'm sure Simplenote can too!

**Comment by theck13** [comment]
Contact us at support@simplenote.com for help.

**Comment by theck13** [comment]
We released a fix for switching between apps in Simplenote Android 2.11.1 and 2.12-rc-2 on October 12th.  Since we haven't received more reports or Play Store reviews about problems switching apps in two weeks, I'm going to close this issue.  Feel free to reopen it if users still have sync issues after updating to Simplenote Android 2.11.1 or 2.12-rc-2.

**Comment by sshaikh** [comment]
Was my report above for 2.11.1 for a different issue? If so is there an issue I can follow the status of?

**Comment by theck13** [comment]
Yes, it is different.  This issue is for switching between apps using the system navigation buttons.  Your case is when exiting the editor and the app before syncing completes.

There isn't a specific issue for your case since the app is working as expected.  Since the app doesn't do anything in the background, exiting the app before syncing completes will save the data locally and sync once the app is opened again.  There are a couple changes we've been considering to sync (i.e. https://github.com/Automattic/simplenote-android/pull/1137 and https://github.com/Automattic/simplenote-android/pull/1184), but nothing is merged yet.

**Comment by sshaikh** [comment]
I didn't realise switching away to the homescreen by pressing home was different to switching to another app. Thanks for the clarification!
